name: Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have an idea that would make Helix better? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or limitation you're running into.
      placeholder: "When building multi-agent pipelines, I often need to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried working around this? What did you consider?
    validations:
      required: false

  - type: textarea
    id: api-sketch
    attributes:
      label: Rough API sketch (optional)
      description: If relevant, sketch what you'd like the API to look like.
      render: python
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      multiple: true
      options:
        - Core (Agent / Team / Workflow)
        - Memory
        - Cache
        - Safety / Budget
        - Models / Providers
        - Eval
        - Observability / Tracing
        - CLI
        - Adapters (LangChain / CrewAI / AutoGen)
        - Documentation
        - Other

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues and this is not already requested.
          required: true
